# Generated by Django 3.2.5 on 2021-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Driving_License_number', models.CharField(max_length=15)),
                ('Vehicle_number', models.CharField(max_length=10)),
                ('Vehicle_color', models.CharField(max_length=10)),
                ('Month_year_of_manufacture', models.DateField()),
                ('Insurance_company_name', models.CharField(max_length=20)),
                ('Insurance_valid_from', models.DateField()),
                ('Insurance_valid_to', models.DateField()),
                ('Pending_Challans', models.IntegerField()),
                ('Address', models.TextField()),
            ],
        ),
    ]
